### ISSUE TITLE
started with ------

### ISSUE THREAD

**Issue by hejuting** [trentm/python-markdown2#249]
It occur error when the markdown text start with '------' and there aren't warp before the '------' .
`
mymarkdown = markdown2.Markdown(
    extras=["code-friendly", "code-color", "cuddled-lists", "fenced-code-blocks", "footnotes", "header-ids",
            "markdown-in-html", "metadata", "nofollow", "numbering", "pyshell",
            "smarty-pants",
            "spoiler", "target-blank-links", "toc", "tables", "use-file-vars", "wiki-tables", "xml", "tag-friendly"]
)
print mymarkdown.convert("------sdfsadfds")
`
eg error:
`
Traceback (most recent call last):
  File "C:/Users/Administrator/PycharmProjects/teamdoc/website/tests.py", line 9, in <module>
    print mymarkdown.convert("------sdfsadfds")
  File "C:\Python27\lib\site-packages\markdown2.py", line 319, in convert
    text = self._extract_metadata(text)
  File "C:\Python27\lib\site-packages\markdown2.py", line 414, in _extract_metadata
    metadata_content = fence_splits[1]
IndexError: list index out of range
`
It works if i add '\n' before the '------'.
eg:
`
print mymarkdown.convert("\n------sdfsadfds")
`
It works if i don't open these extras.
eg:
`
mymarkdown=markdown2.Markdown()
`

**Comment by nicholasserra** [comment]
Thanks for the report! PRs welcome if you want to try to patch this.
