### ISSUE TITLE
Two tests fail (markdown2/tm/issue52_hang [issue52, knownfailure] and markdown2/tm/syntax_color_opts [extra, code-color, pygments])

### ISSUE THREAD

**Issue by mcepl** [trentm/python-markdown2#388]
When building package of markdown2 for OpenSUSE/Factory (from the tarball 2.4.0) I get these failed tests:
```
======================================================================
FAIL: markdown2/tm/issue52_hang [issue52, knownfailure]
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./test_markdown2.py", line 195, in <lambda>
    self._assertMarkdownPath(t, opts=o, toc_html_path=c,
  File "./test_markdown2.py", line 87, in _assertMarkdownPath
    self._assertMarkdown(text, html, text_path, html_path, opts=opts, **extra)
  File "./test_markdown2.py", line 137, in _assertMarkdown
    self.assertEqual(python_norm_html, norm_html, errmsg)
AssertionError: '<ul>\n<li>- - - - - - - - - - - - - - - -[298 chars]l>\n' != 'blah\n'
+ blah
- <ul>
- <li>- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - +
- howdy</li>
- <li><p>- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - +</p>
-
- <p>Privacy Policy:  http://www.PetitionOnline.org/privacy-pets.html</p></li>
- <li><p>- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - +</p></li>
- </ul>
 : markdown2.py didn't produce the expected HTML:
  ---- text (escaping: .=space, \n=newline) ----
    +.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.+\n
    howdy\n
    +.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.+\n
    \n
    ...Privacy.Policy:..http://www.PetitionOnline.org/privacy-pets.html\n
    \n
    +.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.+\n
  ---- Python markdown2.py HTML (escaping: .=space, \n=newline) ----
    <ul>\n
    <li>-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.+\n
    howdy</li>\n
    <li><p>-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.+</p>\n
    \n
    <p>Privacy.Policy:..http://www.PetitionOnline.org/privacy-pets.html</p></li>\n
    <li><p>-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.+</p></li>\n
    </ul>\n
  ---- expected HTML (escaping: .=space, \n=newline) ----
    blah\n
  ---- diff ----
    --- ./tm-cases/issue52_hang.html
    +++ markdown2 ./tm-cases/issue52_hang.text
    @@ -1 +1,8 @@
    -blah
    +<ul>
    +<li>- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - +
    +howdy</li>
    +<li><p>- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - +</p>
    +
    +<p>Privacy Policy:  http://www.PetitionOnline.org/privacy-pets.html</p></li>
    +<li><p>- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - +</p></li>
    +</ul>


======================================================================
FAIL: markdown2/tm/syntax_color_opts [extra, code-color, pygments]
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./test_markdown2.py", line 195, in <lambda>
    self._assertMarkdownPath(t, opts=o, toc_html_path=c,
  File "./test_markdown2.py", line 87, in _assertMarkdownPath
    self._assertMarkdown(text, html, text_path, html_path, opts=opts, **extra)
  File "./test_markdown2.py", line 137, in _assertMarkdown
    self.assertEqual(python_norm_html, norm_html, errmsg)
AssertionError: '<p>H[108 chars] 125%"><span></span><code><span style="color: [874 chars]v>\n' != '<p>H[108 chars] 125%;"><span></span><code><span style="color:[876 chars]v>\n'
  <p>Here is some sample code:</p>

- <div class="codehilite" style="background: #f8f8f8"><pre style="line-height: 125%"><span></span><code><span style="color: #008000; font-weight: bold">import</span> <span style="color: #0000FF; font-weight: bold">sys</span>
+ <div class="codehilite" style="background: #f8f8f8"><pre style="line-height: 125%;"><span></span><code><span style="color: #008000; font-weight: bold">import</span> <span style="color: #0000FF; font-weight: bold">sys</span>
?                                                                                  +
  <span style="color: #008000; font-weight: bold">def</span> <span style="color: #0000FF">main</span>(argv<span style="color: #666666">=</span>sys<span style="color: #666666">.</span>argv):
      logging<span style="color: #666666">.</span>basicConfig()
      log<span style="color: #666666">.</span>info(<span style="color: #BA2121">&#39;hi&#39;</span>)
  </code></pre></div>

  <p>and:</p>

- <div class="codehilite" style="background: #f8f8f8"><pre style="line-height: 125%"><span></span><code>use <span style="color: #BA2121">&#39;zlib&#39;</span>
+ <div class="codehilite" style="background: #f8f8f8"><pre style="line-height: 125%;"><span></span><code>use <span style="color: #BA2121">&#39;zlib&#39;</span>
?                                                                                  +
  <span style="color: #008000">sub</span> main(argv)
      <span style="color: #008000">puts</span> <span style="color: #BA2121">&#39;hi&#39;</span>
  <span style="color: #008000; font-weight: bold">end</span>
  </code></pre></div>
 : markdown2.py didn't produce the expected HTML:
  ---- text (escaping: .=space, \n=newline) ----
    Here.is.some.sample.code:\n
    \n
    ....:::python\n
    ....import.sys\n
    ....def.main(argv=sys.argv):\n
    ........logging.basicConfig()\n
    ........log.info('hi')\n
    \n
    and:\n
    \n
    ....:::ruby\n
    ....use.'zlib'\n
    ....sub.main(argv)\n
    ........puts.'hi'\n
    ....end\n
  ---- Python markdown2.py HTML (escaping: .=space, \n=newline) ----
    <p>Here.is.some.sample.code:</p>\n
    \n
    <div.class="codehilite".style="background:.#f8f8f8"><pre.style="line-height:.125%"><span></span><code><span.style="color:.#008000;.font-weight:.bold">import</span>.<span.style="color:.#0000FF;.font-weight:.bold">sys</span>\n
    <span.style="color:.#008000;.font-weight:.bold">def</span>.<span.style="color:.#0000FF">main</span>(argv<span.style="color:.#666666">=</span>sys<span.style="color:.#666666">.</span>argv):\n
    ....logging<span.style="color:.#666666">.</span>basicConfig()\n
    ....log<span.style="color:.#666666">.</span>info(<span.style="color:.#BA2121">&#39;hi&#39;</span>)\n
    </code></pre></div>\n
    \n
    <p>and:</p>\n
    \n
    <div.class="codehilite".style="background:.#f8f8f8"><pre.style="line-height:.125%"><span></span><code>use.<span.style="color:.#BA2121">&#39;zlib&#39;</span>\n
    <span.style="color:.#008000">sub</span>.main(argv)\n
    ....<span.style="color:.#008000">puts</span>.<span.style="color:.#BA2121">&#39;hi&#39;</span>\n
    <span.style="color:.#008000;.font-weight:.bold">end</span>\n
    </code></pre></div>\n
  ---- expected HTML (escaping: .=space, \n=newline) ----
    <p>Here.is.some.sample.code:</p>\n
    \n
    <div.class="codehilite".style="background:.#f8f8f8"><pre.style="line-height:.125%;"><span></span><code><span.style="color:.#008000;.font-weight:.bold">import</span>.<span.style="color:.#0000FF;.font-weight:.bold">sys</span>\n
    <span.style="color:.#008000;.font-weight:.bold">def</span>.<span.style="color:.#0000FF">main</span>(argv<span.style="color:.#666666">=</span>sys<span.style="color:.#666666">.</span>argv):\n
    ....logging<span.style="color:.#666666">.</span>basicConfig()\n
    ....log<span.style="color:.#666666">.</span>info(<span.style="color:.#BA2121">&#39;hi&#39;</span>)\n
    </code></pre></div>\n
    \n
    <p>and:</p>\n
    \n
    <div.class="codehilite".style="background:.#f8f8f8"><pre.style="line-height:.125%;"><span></span><code>use.<span.style="color:.#BA2121">&#39;zlib&#39;</span>\n
    <span.style="color:.#008000">sub</span>.main(argv)\n
    ....<span.style="color:.#008000">puts</span>.<span.style="color:.#BA2121">&#39;hi&#39;</span>\n
    <span.style="color:.#008000;.font-weight:.bold">end</span>\n
    </code></pre></div>\n
  ---- diff ----
    --- ./tm-cases/syntax_color_opts.html
    +++ markdown2 ./tm-cases/syntax_color_opts.text
    @@ -1,6 +1,6 @@
     <p>Here is some sample code:</p>

    -<div class="codehilite" style="background: #f8f8f8"><pre style="line-height: 125%;"><span></span><code><span style="color: #008000; font-weight: bold">import</span> <span style="color: #0000FF; font-weight: bold">sys</span>
    +<div class="codehilite" style="background: #f8f8f8"><pre style="line-height: 125%"><span></span><code><span style="color: #008000; font-weight: bold">import</span> <span style="color: #0000FF; font-weight: bold">sys</span>
     <span style="color: #008000; font-weight: bold">def</span> <span style="color: #0000FF">main</span>(argv<span style="color: #666666">=</span>sys<span style="color: #666666">.</span>argv):
         logging<span style="color: #666666">.</span>basicConfig()
         log<span style="color: #666666">.</span>info(<span style="color: #BA2121">&#39;hi&#39;</span>)
    @@ -8,7 +8,7 @@

     <p>and:</p>

    -<div class="codehilite" style="background: #f8f8f8"><pre style="line-height: 125%;"><span></span><code>use <span style="color: #BA2121">&#39;zlib&#39;</span>
    +<div class="codehilite" style="background: #f8f8f8"><pre style="line-height: 125%"><span></span><code>use <span style="color: #BA2121">&#39;zlib&#39;</span>
     <span style="color: #008000">sub</span> main(argv)
         <span style="color: #008000">puts</span> <span style="color: #BA2121">&#39;hi&#39;</span>
     <span style="color: #008000; font-weight: bold">end</span>
```

[Full build log](https://github.com/trentm/python-markdown2/files/5883674/_log.txt) contains all details of the build including versions of all packages used.

**Comment by nicholasserra** [comment]
Looks like you're running an older version of Pygments, likely causing the failures.

**Comment by mcepl** [comment]
What is the minimal required version?

**Comment by nicholasserra** [comment]
I'm the maintainer of this package. It's not added anywhere because it's an optional package and only required for code highlighting and a couple tests. 

We add it here in ci:
https://github.com/trentm/python-markdown2/blob/master/.travis.yml#L11

Anyway, try 2.7.3 or 2.7.4.

**Comment by mcepl** [comment]
@nicholasserra This is incorrect ... ``curl -L -s https://github.com/trentm/python-markdown2/files/5883674/_log.txt|grep -i pygments`` gives you Pygments version 2.6.1, so 2.5.2 is obviously not enough.
