### ISSUE TITLE
TypeError when using fenced-code-blocks with latest version of pygments (2.12.0)

### ISSUE THREAD

**Issue by philgyford** [trentm/python-markdown2#438]
The lates release of pygments (2.12.0, 2022-04-24) [includes a change](https://github.com/pygments/pygments/blob/master/CHANGES#L66) to the signature of `HtmlFormatter.wrap()`:

> If you have subclassed ``HtmlFormatter.wrap``, you may have to adjust the logic.

I don't understand what the change *is* from those release notes though. However, using pygments v2.12.0 with markdown2 v2.4.2 generates a TypeError when using the fenced-code-blocks extra (and maybe other extras; this is where I noticed it):

```python
import markdown2

s = """```python
if True:
    print("hi")
```"""

markdown2.markdown(s, extras=["fenced-code-blocks"])

Traceback (most recent call last):
  File "/Users/phil/.local/share/virtualenvs/personal-Q4oMkqbN/lib/python3.10/site-packages/pygments/__init__.py", line 61, in format
    formatter.format(tokens, realoutfile)
  File "/Users/phil/.local/share/virtualenvs/personal-Q4oMkqbN/lib/python3.10/site-packages/pygments/formatter.py", line 94, in format
    return self.format_unencoded(tokensource, outfile)
  File "/Users/phil/.local/share/virtualenvs/personal-Q4oMkqbN/lib/python3.10/site-packages/pygments/formatters/html.py", line 981, in format_unencoded
    source = self.wrap(source)
TypeError: Markdown._color_with_pygments.<locals>.HtmlCodeFormatter.wrap() missing 1 required positional argument: 'outfile'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/phil/.local/share/virtualenvs/personal-Q4oMkqbN/lib/python3.10/site-packages/markdown2.py", line 184, in markdown
    use_file_vars=use_file_vars, cli=cli).convert(text)
  File "/Users/phil/.local/share/virtualenvs/personal-Q4oMkqbN/lib/python3.10/site-packages/markdown2.py", line 353, in convert
    text = self._do_fenced_code_blocks(text)
  File "/Users/phil/.local/share/virtualenvs/personal-Q4oMkqbN/lib/python3.10/site-packages/markdown2.py", line 1942, in _do_fenced_code_blocks
    return self._fenced_code_block_re.sub(self._fenced_code_block_sub, text)
  File "/Users/phil/.local/share/virtualenvs/personal-Q4oMkqbN/lib/python3.10/site-packages/markdown2.py", line 1938, in _fenced_code_block_sub
    return self._code_block_sub(match, is_fenced_code_block=True)
  File "/Users/phil/.local/share/virtualenvs/personal-Q4oMkqbN/lib/python3.10/site-packages/markdown2.py", line 1882, in _code_block_sub
    colored = self._color_with_pygments(codeblock, lexer,
  File "/Users/phil/.local/share/virtualenvs/personal-Q4oMkqbN/lib/python3.10/site-packages/markdown2.py", line 1842, in _color_with_pygments
    return pygments.highlight(codeblock, lexer, formatter)
  File "/Users/phil/.local/share/virtualenvs/personal-Q4oMkqbN/lib/python3.10/site-packages/pygments/__init__.py", line 82, in highlight
    return format(lex(code, lexer), formatter, outfile)
  File "/Users/phil/.local/share/virtualenvs/personal-Q4oMkqbN/lib/python3.10/site-packages/pygments/__init__.py", line 69, in format
    raise TypeError('format() argument must be a formatter instance, '
TypeError: format() argument must be a formatter instance, not a class
```

**Comment by nicholasserra** [comment]
Thanks for the report!

@philgyford if you have a moment, wanna give it a try with this fix? https://github.com/trentm/python-markdown2/pull/437

I won't have time to test it out until later in the week.

**Comment by nicholasserra** [comment]
Fix merged from https://github.com/trentm/python-markdown2/pull/437

Will release a new version to pypi asap.
